apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  namespace: default
spec:
  containers:
  - name: myapp
    image: ironcrush2006/kubetest:1.0
    ports:
    - containerPort: 3000  # Corrected from 'containerPorts' to 'containerPort'
    env:
    - name: APP_VERSION
      valueFrom:
        configMapKeyRef:
          name: app
          key: app_version 
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi  # This line is already correct